### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by grahamperrin** [tiansh/always-in-container#7]
From <https://github.com/mozilla/multi-account-containers/issues/2001#issuecomment-826467089> (not my question): 

> wouldn't there be any security issues using _Always In Container_? …

From [Add-on Badges | Firefox Help](https://support.mozilla.org/en-US/kb/add-on-badges): 

> … Most extensions are created by trustworthy developers. …

----

@naoliden for the other part of your question, https://github.com/mozilla/multi-account-containers/issues/2001#issuecomment-827304254

**Comment by tiansh** [comment]
I'm glad to see some other extensions, especially something like [MAC](https://github.com/mozilla/multi-account-containers), may have similar features included. So I won't need to maintain this extension but get same functionally to my Firefox.
I will however try my best to fix any security issues if anyone may find out some.
Although I'm not aimed to create vulnerable extensions. This extension, as comes with MPL-2.0: _"without warranty of any kind, either expressed, implied, or statutory, including, without limitation, warranties that the Covered Software is free of defects, merchantable, fit for a particular purpose or non-infringing"_

**Comment by grahamperrin** [comment]
Thank you. 

![image](https://user-images.githubusercontent.com/192271/116314334-dd0da200-a7a6-11eb-8d57-7a6738625003.png)

https://support.mozilla.org/en-US/kb/permission-request-messages-firefox-extensions#w_access-your-data-for-all-websites _Access your data for all websites_

https://support.mozilla.org/en-US/kb/permission-request-messages-firefox-extensions#w_access-browser-tabs _Access browser tabs_ 

Please, can the extension work as well **without** data for all websites?

**Comment by tiansh** [comment]
> Please, can the extension work as well **without** data for all websites?

This extension use very same logic as what MAC do. Also some source codes are based on MAC. As a result, it requires same permissions like what MAC do. That permissions helps extension to stop / cancel web requests out of containers. I didn't see a better way to exclude these permissions. Fell free to comment / PR / fork if you have any idea of improvements.

**Comment by grahamperrin** [comment]
Thanks for the explanation. 

I had not thought to compare with permissions for Multi-Account Containers: 

![image](https://user-images.githubusercontent.com/192271/116360759-23d7b800-a7f8-11eb-84fd-8d36b3693c7f.png)

https://github.com/mozilla/multi-account-containers/wiki/Permissions

I'm not a developer, so (for Always In Container) I can not imagine an alternative permissions model.
