### ISSUE TITLE
Enhancement request: allow something other than a container to be chosen

### ISSUE THREAD

**Issue by grahamperrin** [tiansh/always-in-container#8]
Ignoring, for a moment, _Always In Container_ as the name of the extension …

----

Please: is it possible for the extension page to include **no container** as a choice? 

Can this be done, without breaking the method of detection for a link that is _initially_ non-contained? 

(I don't understand the code, but I can imagine things 'looping back' to the extension page.)

### Rough mock-up

![image](https://user-images.githubusercontent.com/192271/116516539-a0849800-a8c5-11eb-98d6-5f2d2ce62512.png)

* **… no container** as one of two buttons _below_ the array of containers
* the second button is notionally for #5

**Comment by tiansh** [comment]
No container option won't ever work. This extension will try to block every page load without container. And as a result, if you try to navigate the page after you choice "no container", this extension will ask the same question again and again... And maybe, you are looking for some other extensions as it really not something called "always in container".

**Comment by grahamperrin** [comment]
Thanks. Understood, the loop. 

Instead, the user can simply add a container that is **notionally equivalent** to _no container_: 

![image](https://user-images.githubusercontent.com/192271/116519875-e6dbf600-a8c9-11eb-84da-4a9ffa4ab6be.png)

* I chose to name it _undecided_
* someone else might prefer to name it _don't care_ or _everything else_ or whatever. 

The URL used for this screenshot: <https://man.freebsd.org/hier(7)> 

### Considerations

* [Firefox 85 Cracks Down on Supercookies - Mozilla Security Blog](https://blog.mozilla.org/security/2021/01/26/supercookie-protections/)
* [Firefox 86 Introduces Total Cookie Protection - Mozilla Security Blog](https://blog.mozilla.org/security/2021/02/23/total-cookie-protection/)
* [Introducing State Partitioning - Mozilla Hacks - the Web developer blog](https://hacks.mozilla.org/2021/02/introducing-state-partitioning/)
* https://github.com/mozilla/multi-account-containers/issues/1974

**Comment by janmechtel** [comment]
@tiansh I love the extension in general! because it helps me clicking on links and then being asked about the container.

I came here because i was looking to add support for private windows.

>And maybe, you are looking for some other extensions as it really not something called "always in container".
Do you mean that as a design choice? Do you not want to support private windows because they are not containers? Or could I look into how that would be possible?
